import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Button, Container, Stack, ThemeProvider } from "@mui/material";
import theme from "@/themes";
import { SignupForm } from "@/components/SignupForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        {/*
        <Stack spacing="8px"
        sx={{
          mt: 2,
          px: 2,
          height: "100vh",
        }}
        alignItems = "flex-start"
        justifyContent = "center"
        >

        <Box><Button  variant="contained">Hello</Button></Box>
        <Button  variant="outlined">Hello World</Button>
        <Button  variant="text">Hello World</Button>
        <Button  variant="contained" color="secondary">Hello World</Button>
        <Button  variant="outlined" color="secondary">Hello World</Button>
        <Button  variant="text" color="secondary">Hello World</Button>
          <Stack direction="row" width="100%" spacing={2} justifyContent="center">
            <Button sx={{flex: 1}} variant="contained">Hello World</Button>
            <Button sx={{flex: 2}} variant="outlined">Hello World</Button>
            <Button variant="text">Hello World</Button>
          </Stack>
        </Stack>
        */}
        <Container maxWidth="md">
          <SignupForm />
        </Container>
      </ThemeProvider>
    </>
  );
}
